apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: C1
  template:
    metadata:
      labels:
        app: C1
    spec:
      containers:
        - name: service-kuber
          image: haridtvt/pratices:12
          ports:
            - containerPort: 80
