apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deployment_node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: Worker_node1
  template:
    metadata:
      labels:
        app: Work_node1
    spec:
      containers:
        - name: service-kuber
          image: haridtvt/pratices:12
          ports:
            - containerPort: 80
